### PR TITLE
Create codeql-analysis.yml

### PR DESCRIPTION
**Pull request by XVilka**
**Detailed description**

...

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Comment by XVilka** [comment]
It found the following alerts: https://github.com/radareorg/radare2-webui/security/code-scanning?query=tool%3ACodeQL+is%3Aopen+ref%3Arefs%2Fpull%2F174%2Fhead

**Comment by XVilka** [comment]
Also note the following outdated dependencies alerts: https://github.com/radareorg/radare2-webui/network/alerts

**Comment by trufae** [comment]
It is possible to have a badge for codeql and lgtm? Do  you mind adding them in this same PR? thank you!

**Comment by trufae** [comment]
ill add the badge

**Pull request merged**
